name: Nix
permissions: {}
on:
  workflow_dispatch:
    inputs:
      os:
        description: OS to run
        required: true
        type: choice
        options: 
          - linux
          - darwin
          - aarch64-darwin
          - x86_64-darwin
          - all
        default: aarch64-darwin
jobs:
  nix:
    strategy:
      fail-fast: false
      matrix:
        os: >-
          ${{ fromJSON(
            inputs.os == 'linux' && '["ubuntu-latest"]' || (
            inputs.os == 'darwin' && '["macos-latest", "macos-13"]' || (
            inputs.os == 'aarch64-darwin' && '["macos-latest"]' || (
            inputs.os == 'x86_64-darwin' && '["macos-13"]' || (
            '["ubuntu-latest", "macos-latest", "macos-13"]'
          ))))) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: exec ./.github/workflows/debug.sh
